services:
  api_gateway:
    container_name: api_gateway
    build: ./api_gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - USER_SERVICE_URL=http://user_api:5001
      - AUTH_SERVICE_URL=http://authentification_api:5002
      - CLIENT_SERVICE_URL=http://client_api:5003
      - ITEM_SERVICE_URL=http://item_api:5004
      - LOGS_SERVICE_URL=http://logs_api:5050
    networks:
      - app-network
    depends_on:
      - user_api
      - authentification_api
      - client_api
      - item_api
      - logs_api

  logs_api:
    container_name: logs_api
    build:
      context: ./backend/logs_api
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./backend/logs_api:/app
      - ./backend/logs_api/logs:/app/logs
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  authentification_api:
    container_name: authentification_api
    build:
      context: ./backend/authentification_api
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - DB_USER=jordans
      - DB_HOST=postgres_db
      - DB_NAME=SLI
      - DB_PASSWORD=slitest
      - DB_PORT=5432
    volumes:
      - ./backend/authentification_api:/app
      - /app/node_modules
      - ./backend/authentification_api/logs:/app/logs
    networks:
      - app-network

  user_api:
    container_name: user_api
    build:
      context: ./backend/user_api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DB_USER=jordans
      - DB_HOST=postgres_db
      - DB_NAME=SLI
      - DB_PASSWORD=slitest
      - DB_PORT=5432
    volumes:
      - ./backend/user_api:/app
      - /app/node_modules
      - ./backend/middlewares:/app/middlewares 
    networks:
      - app-network

  client_api:
    container_name: client_api
    build:
      context: ./backend/client_api
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - DB_USER=jordans
      - DB_HOST=postgres_db
      - DB_NAME=SLI
      - DB_PASSWORD=slitest
      - DB_PORT=5432
      - REDIS_URL=redis://client_redis:6379
    volumes:
      - ./backend/client_api:/app
      - /app/node_modules
      - ./backend/client_api/logs:/app/logs
    networks:
      - app-network
    depends_on:
      - postgres_db
      - client_redis

  item_api:
    container_name: item_api
    build:
      context: ./backend/item_api
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    environment:
      - DB_USER=jordans
      - DB_HOST=postgres_db
      - DB_NAME=SLI
      - DB_PASSWORD=slitest
      - DB_PORT=5432
    volumes:
      - ./backend/item_api:/app
      - /app/node_modules
      - ./backend/middlewares:/app/middlewares
    networks:
      - app-network

  postgres_db:
    container_name: postgres_db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: jordans
      POSTGRES_PASSWORD: slitest
      POSTGRES_DB: SLI
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./BackupBDD:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network

  client_redis:
    image: redis:6.2
    container_name: client_redis
    volumes:
      - client_redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  client_redis_data:
    driver: local
