services:
  user_api:
    build:
      context: ./backend/user_api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DB_USER=jordans
      - DB_HOST=host.docker.internal
      - DB_NAME=SLI
      - DB_PASSWORD=slitest
      - DB_PORT=5432
    volumes:
      - ./backend/user_api:/app
      - /app/node_modules
      - ./backend/middlewares:/app/middlewares 

  client_api:
    container_name: client_api
    build:
      context: ./backend/client_api
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - DB_USER=jordans
      - DB_HOST=host.docker.internal
      - DB_NAME=SLI
      - DB_PASSWORD=slitest
      - DB_PORT=5432
    volumes:
      - ./backend/client_api:/app
      - /app/node_modules
      - ./backend/middlewares:/app/middlewares

  authentification_api:
    build:
      context: ./backend/authentification_api
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - DB_USER=jordans
      - DB_HOST=host.docker.internal
      - DB_NAME=SLI
      - DB_PASSWORD=slitest
      - DB_PORT=5432
    volumes:
      - ./backend/authentification_api:/app
      - /app/node_modules
      - ./backend/middlewares:/app/middlewares 

  item_api:
    container_name: item_api
    build:
      context: ./backend/item_api
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    environment:
      - DB_USER=jordans
      - DB_HOST=host.docker.internal
      - DB_NAME=SLI
      - DB_PASSWORD=slitest
      - DB_PORT=5432
    volumes:
      - ./backend/item_api:/app
      - /app/node_modules
      - ./backend/middlewares:/app/middlewares


  
  sli_mobile:
    image: node:20-alpine
    ports:
      - "19006:19006"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    volumes:
      - ./sli_mobile:/opt/react_native_app/app:delegated
      - notused:/opt/react_native_app/app/node_modules
    environment:
      - EXPO_DEBUG=true
    command: ["npx", "expo", "start", "--offline", "--no-dev"]

  postgres:
    image: postgres:latest
    container_name: postgres_restore
    environment:
      POSTGRES_USER: jordans
      POSTGRES_PASSWORD: slitest
      POSTGRES_DB: SLI
    volumes:
      - type: bind
        source: C:/Users/jorda/OneDrive/Bureau/VM/Partage VM-Tinkerbell-Kali/Dump DB SLI/volume_backup/volume
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  notused:
