services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - USER_SERVICE_URL=http://user_api:5001
      - AUTH_SERVICE_URL=http://authentification_api:5002
      - CLIENT_SERVICE_URL=http://client_api:5003
      - ITEM_SERVICE_URL=http://item_api:5004
    networks:
      - app-network
    depends_on:
      - user_api
      - authentification_api
      - client_api
      - item_api
      
  user_api:
    build:
      context: ./backend/user_api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DB_USER=jordans
      - DB_HOST=host.docker.internal
      - DB_NAME=SLI
      - DB_PASSWORD=slitest
      - DB_PORT=5432
    volumes:
      - ./backend/user_api:/app
      - /app/node_modules
      - ./backend/middlewares:/app/middlewares 
    networks:
      - app-network

  client_api:
    container_name: client_api
    build:
      context: ./backend/client_api
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - DB_USER=jordans
      - DB_HOST=host.docker.internal
      - DB_NAME=SLI
      - DB_PASSWORD=slitest
      - DB_PORT=5432
    volumes:
      - ./backend/client_api:/app
      - /app/node_modules
      - ./backend/client_api/logs:/app/logs

    networks:
      - app-network

  authentification_api:
    build:
      context: ./backend/authentification_api
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - DB_USER=jordans
      - DB_HOST=host.docker.internal
      - DB_NAME=SLI
      - DB_PASSWORD=slitest
      - DB_PORT=5432
    volumes:
      - ./backend/authentification_api:/app
      - /app/node_modules
      - ./backend/authentification_api/logs:/app/logs
    networks:
      - app-network

  item_api:
    container_name: item_api
    build:
      context: ./backend/item_api
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    environment:
      - DB_USER=jordans
      - DB_HOST=host.docker.internal
      - DB_NAME=SLI
      - DB_PASSWORD=slitest
      - DB_PORT=5432
    volumes:
      - ./backend/item_api:/app
      - /app/node_modules
      - ./backend/middlewares:/app/middlewares
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
