services:

  synchro_api:
    container_name: synchro_api
    build:
      context: ./backend/synchro_api
      dockerfile: Dockerfile
    ports:
      - "5007:5007"
    environment:
      - DB_USER=jordans
      - DB_HOST=host.docker.internal
      - DB_NAME=SLI
      - DB_PASSWORD=slitest
      - DB_PORT=5432
    volumes:
      - ./backend/synchro_api:/app
      - /app/node_modules
      - ./backend/middlewares:/app/middlewares
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: jordans
      POSTGRES_PASSWORD: slitest
      POSTGRES_DB: SLI
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
