export interface Item {
    Date: Date;
    BarcodePrice: number;
    BarcodeWeight: number;
    PosAddItem: boolean;
    LoyaltyPoints: number;
    CalculateLoyaltyFrom: number;
    GiftVoucher: boolean;
    IntrastatExcluded: boolean;
    CreateCustomerProductInCustomerPark: boolean;
    IsMaintenanceContract: boolean;
    IsGuaranteeExtension: boolean;
    CustomerParkCreation: number;
    StockBookingAllowed: boolean | number;
    AutomaticStockBooking: boolean;
    IncludeToRecursiveReplenishment: boolean;
    IncludeToFabricationReplenishment: boolean;
    IncludeToSupplierReplenishment: boolean;
    CadenceQuantity: number;
    CadenceNumberOfDays: number;
    DoNotAssortAssemblyRequestsWithDifferentDates: boolean;
    MaximumGapDayToAssort: number;
    NomenclatureAccountingTransferTypeForSale: number;
    NomenclatureAccountingTransferTypeForPurchase: number;
    VirtualPump: boolean;
    VirtualStockValue: number;
    BookedQuantity: number;
    PurchaseBillOfQuantitiesProgramKeepActiveFromQuoteToOrder: boolean;
    NotOnMarket: boolean;
    PurchaseUnitPriceProgramKeepActiveFromQuoteToOrder: boolean;
    CanBePartiallyDelivered: boolean;
    Caption: string;
    OxatisOxatisHandlingSurcharge1St: number;
    OxatisOxatisHandlingSurchargeOthers: number;
    InterventionDurationEqualsQuantity: boolean;
    Height: number;
    Width: number;
    Length: number;
    FamilyId: string;
    OxatisOxatisUseSubFamilyAsBrand: boolean;
    IsManagedByCounterMark: boolean;
    IsCounterMarkForced: boolean;
    SalePurchaseConversionRate: number;
    LimitDateMode: number;
    LimitDateSafetyDelay: number;
    UniqueId: string;
    PurchasePrice: number;
    ChargeRate: number;
    ChargeAmount: number;
    CostPrice: number;
    InterestRate: number;
    InterestAmount: number;
    SalePriceVatExcluded: number;
    BrandRate: number;
    VatAmount: number;
    SalePriceVatIncluded: number;
    ManageStock: boolean;
    RealStock: number;
    Pump: number;
    StockValue: number;
    OrderedQuantity: number;
    SuppliersOrderedQuantity: number;
    VirtualStock: number;
    DefaultQuantity: number;
    Volume: number;
    Weight: number;
    NetWeight: number;
    ComponentsPurchasePrice: number;
    ComponentsCostPrice: number;
    ComponentsSalePriceVatExcluded: number;
    ComponentsSalePriceVatIncluded: number;
    PrintComponentDetail: number;
    AssemblingVirtualQuantity: number;
    DisassemblingQuantity: number;
    QuantityUsedToAssemblate: number;
    QuantityFromDisassembling: number;
    AllowNegativeStock: boolean;
    UseComponentVat: boolean;
    ApplyPriceListOnComponents: boolean;
    ActiveState: number;
    AdvisedSalePriceVatExcluded: number;
    SetItemSalePriceWithAdvisedSalePrice: boolean;
    TrackingMode: number;
    AllowComponentsModification: boolean;
    AllowPublishOnWeb: boolean;
    ImageVersion: number;
    PriceDecimalNumber: number;
    IsHumanServicesIncludedInAttestation: boolean;
    OxatisOxatisShowInStockNote: boolean;
    OxatisOxatisShowStockLevel: boolean;
    OxatisOxatisShowIfOutOfStock: boolean;
    OxatisOxatisSaleIfOutOfStock: boolean;
    OxatisOxatisSaleIfOutOfStockScenario: number;
    OxatisOxatisShowDaysToShip: boolean;
    OxatisOxatisShipPrice: number;
    OxatisOxatisDaysToShip: number;
    OxatisOxatisUserMainSupplierDaysToShip: boolean;
    Id: string;
    ItemType: number;
    BillOfQuantitiesProgramKeepActiveFromQuoteToOrder: boolean;
    SaleUnitPriceProgramKeepActiveFromQuoteToOrder: boolean;
    UpdateComponentsStockInFabrication: boolean;
    CustomersDeliveryOrderPreparingQuantity: number;
    CustomersReturnOrderPreparingQuantity: number;
    SuppliersDeliveryOrderPreparingQuantity: number;
    SuppliersReturnOrderPreparingQuantity: number;
    StockBillOfQuantitiesProgramKeepActiveFromQuoteToOrder: boolean;
    PurchaseChargesRate: number;
    PosIsScale: boolean;
    PosTare: string | null;
    ReplenishmentDeliveryAddressType: number;
    ItemImage: string | null;
    DesCom: string;
    DesComClear: string;
    OxatisOxatisMetaTitle: string | null;
    OxatisOxatisMetaDescription: string | null;
    OxatisOxatisMetaKeywords: string | null;
    OxatisOxatisBrand: string | null;
    MainIntervener: string | null;
    IntrastatNc8NomenclatureId: string | null;
    Group1: string | null;
    Group2: string | null;
    NotPrintable: boolean | null;
    NotIncluded: boolean | null;
    IsFixedPrice: boolean | null;
    NonInvoiceableType: number | null;
    ComponentCalculationType: number | null;
    ReplacementItem: string | null;
    WeightUnitId: string | null;
    NumberOfItemByPackage: number;
    VolumeUnitId: string | null;
    SupplierId: string;
    EcotaxId: string | null;
    StockDestination: number;
    StockVarianceAccount: string;
    CurrentStockAccount: string;
    VatId: string;
    SysModuleId: string | null;
    SysDatabaseId: string | null;
    SysRecordVersion: number;
    SysRecordVersionId: string;
    SysEditCounter: number;
    LimitDateSafetyDelayMode: number | null;
    DefaultLifetime: number | null;
    PurchasePriceUpdateType: number | null;
    AnalyticAccountingGridId: string | null;
    PurchaseUnitId: string | null;
    DimensionUnitId: string | null;
    OxatisOxatisLongDescription: string | null;
    OxatisOxatisLongDescriptionClear: string | null;
    OxatisOxatisSmallImage: string | null;
    PurchaseBillOfQuantitiesProgramProgram: string | null;
    CatalogId: string | null;
    CatalogItemId: string | null;
    EcotaxFurnitureId: string | null;
    PurchaseUnitPriceProgramProgram: string | null;
    LocalizableCaption2: string | null;
    LocalizableDesCom2: string | null;
    LocalizableDesComClear2: string | null;
    LocalizableCaption3: string | null;
    LocalizableCaption4: string | null;
    LocalizableCaption5: string | null;
    LocalizableDesCom3: string | null;
    LocalizableDesComClear3: string | null;
    LocalizableDesCom4: string | null;
    LocalizableDesComClear4: string | null;
    LocalizableDesCom5: string | null;
    LocalizableDesComClear5: string | null;
    IntrastatOriginCountryId: string | null;
    ParentRangeItemId: string | null;
    RangeTypeElementId0: string | null;
    RangeTypeElementId1: string | null;
    RangeTypeElementId2: string | null;
    RangeTypeElementId3: string | null;
    RangeTypeElementId4: string | null;
    DefaultAllowedStorehouseId: string | null;
    MaintenanceContractTemplateId: string | null;
    GuaranteeTypeId: string | null;
    StockBillOfQuantitiesProgramProgram: string | null;
    PosThumbnail: string | null;
    GiftVoucherCashValue: number | null;
    GiftVoucherValidityDuration: number | null;
    IsExtraFee: boolean;
    TimeUnitId: string | null;
    TechnicalDesCom: string | null;
    TechnicalDesComClear: string | null;
    LocalizableTechnicalDesCom2: string | null;
    LocalizableTechnicalDesComClear2: string | null;
    LocalizableTechnicalDesCom3: string | null;
    LocalizableTechnicalDesComClear3: string | null;
    LocalizableTechnicalDesCom4: string | null;
    LocalizableTechnicalDesComClear4: string | null;
    LocalizableTechnicalDesCom5: string | null;
    LocalizableTechnicalDesComClear5: string | null;
    CompetenceId: string | null;
    EquipmentTypeId: string | null;
    ScheduleEventTemplateId: string | null;
    CompetenceNumberToPlan: number | null;
    EquipmentTypeNumberToPlan: number | null;
    CadenceDuration: number;
    CadenceDurationType: number;
    CadenceDurationQuantity: number;
    InstallationTime: number;
    LabourCode: string | null;
    AutoUpdateLabourPrice: boolean;
    IsEquipment: boolean;
    InstallationCalculationType: number;
    MaterialPricesPurchasePrice: number;
    MaterialPricesChargeRate: number;
    MaterialPricesChargeAmount: number;
    MaterialPricesCostPrice: number;
    MaterialPricesInterestRate: number;
    MaterialPricesInterestAmount: number;
    MaterialPricesSalePriceVatExcluded: number;
    MaterialPricesBrandRate: number;
    MaterialPricesVatId: string;
    MaterialPricesVatAmount: number;
    MaterialPricesSalePriceVatIncluded: number;
    MaterialPricesAdvisedSalePriceVatExcluded: number;
    MaterialPricesSetItemSalePriceWithAdvisedSalePrice: boolean;
    MaterialPricesIsFixedPrice: boolean | null;
    MaterialPricesEcotaxFurnitureId: string | null;
    LabourPricesPurchasePrice: number;
    LabourPricesChargeRate: number;
    LabourPricesChargeAmount: number;
    LabourPricesCostPrice: number;
    LabourPricesInterestRate: number;
    LabourPricesInterestAmount: number;
    LabourPricesSalePriceVatExcluded: number;
    LabourPricesBrandRate: number;
    LabourPricesVatId: string;
    LabourPricesVatAmount: number;
    LabourPricesSalePriceVatIncluded: number;
    LabourPricesAdvisedSalePriceVatExcluded: number;
    LabourPricesSetItemSalePriceWithAdvisedSalePrice: boolean;
    LabourPricesIsFixedPrice: boolean | null;
    LabourPricesEcotaxFurnitureId: string | null;
    CanBePartiallyInvoiced: boolean;
    PickMovementDisallowedOnTotallyBookedItem: boolean;
    SalePriceModifiedDate: string | null;
    SalePriceModifiedUserId: string | null;
    TarifeoCode: string | null;
    TarifeoFullCode: string | null;
    TarifeoProducerId: string | null;
    ProducerName: string | null;
    TarifeoPriceDate: string | null;
    TarifeoPriceVersion: string | null;
    TarifeoUpdateDatetime: string | null;
    IsSubscription: boolean;
    SubscriptionPassings: number;
    SubscriptionTotalCostPrice: number;
    SubscriptionTotalPurchasePrice: number;
    SubscriptionTotalSalePriceVatExcluded: number;
    SubscriptionValidityDuration: number;
    id: number;
  }
  
  
  
  /*export interface Item {
      date: date;
      barcodeprice: number;
      barcodeweight: number;
      posadditem: boolean;
      loyaltypoints: number;
      calculateloyaltyfrom: number;
      giftvoucher: boolean;
      intrastatexcluded: boolean;
      createcustomerproductincustomerpark: boolean;
      ismaintenancecontract: boolean;
      isguaranteeextension: boolean;
      customerparkcreation: number;
      stockbookingallowed: boolean | number;    //MODIFIER PERSO
      automaticstockbooking: boolean;
      includetorecursivereplenishment: boolean;
      includetofabricationreplenishment: boolean;
      includetosupplierreplenishment: boolean;
      cadencequantity: number;
      cadencenumberofdays: number;
      donotassortassemblyrequestswithdifferentdates: boolean;
      maximumgapdaytoassort: number;
      nomenclatureaccountingtransfertypeforsale: number;
      nomenclatureaccountingtransfertypeforpurchase: number;
      virtualpump: boolean;
      virtualstockvalue: number;
      bookedquantity: number;
      purchasebillofquantitiesprogram_keepactivefromquotetoorder: boolean;
      notonmarket: boolean;
      purchaseunitpriceprogram_keepactivefromquotetoorder: boolean;
      canbepartiallydelivered: boolean;
      caption: string;
      oxatis_oxatis_handlingsurcharge1st: number;
      oxatis_oxatis_handlingsurchargeothers: number;
      interventiondurationequalsquantity: boolean;
      height: number;
      width: number;
      length: number;
      oxatis_oxatis_usesubfamilyasbrand: boolean;
      ismanagedbycountermark: boolean;
      iscountermarkforced: boolean;
      salepurchaseconversionrate: number;
      limitdatemode: number;
      limitdatesafetydelay: number;
      uniqueid: string;
      purchaseprice: number;
      chargerate: number;
      chargeamount: number;
      costprice: number;
      interestrate: number;
      interestamount: number;
      salepricevatexcluded: number;
      brandrate: number;
      vatamount: number;
      salepricevatincluded: number;
      managestock: boolean;
      realstock: number;
      pump: number;
      stockvalue: number;
      orderedquantity: number;
      suppliersorderedquantity: number;
      virtualstock: number;
      defaultquantity: number;
      volume: number;
      weight: number;
      netweight: number;
      componentspurchaseprice: number;
      componentscostprice: number;
      componentssalepricevatexcluded: number;
      componentssalepricevatincluded: number;
      printcomponentdetail: number;
      assemblingvirtualquantity: number;
      disassemblingquantity: number;
      quantityusedtoassemblate: number;
      quantityfromdisassembling: number;
      allownegativestock: boolean;
      usecomponentvat: boolean;
      applypricelistoncomponents: boolean;
      activestate: number;
      advisedsalepricevatexcluded: number;
      setitemsalepricewithadvisedsaleprice: boolean;
      trackingmode: number;
      allowcomponentsmodification: boolean;
      allowpublishonweb: boolean;
      imageversion: number;
      pricedecimalnumber: number;
      ishumanservicesincludedinattestation: boolean;
      oxatis_oxatis_showinstocknote: boolean;
      oxatis_oxatis_showstocklevel: boolean;
      oxatis_oxatis_showifoutofstock: boolean;
      oxatis_oxatis_saleifoutofstock: boolean;
      oxatis_oxatis_saleifoutofstockscenario: number;
      oxatis_oxatis_showdaystoship: boolean;
      oxatis_oxatis_shipprice: number;
      oxatis_oxatis_daystoship: number;
      oxatis_oxatis_usermainsupplierdaystoship: boolean;
      id: string;
      itemtype: number;
      billofquantitiesprogram_keepactivefromquotetoorder: boolean;
      saleunitpriceprogram_keepactivefromquotetoorder: boolean;
      updatecomponentsstockinfabrication: boolean;
      customersdeliveryorderpreparingquantity: number;
      customersreturnorderpreparingquantity: number;
      suppliersdeliveryorderpreparingquantity: number;
      suppliersreturnorderpreparingquantity: number;
      stockbillofquantitiesprogram_keepactivefromquotetoorder: boolean;
      purchasechargesrate: number;
      posisscale: boolean;
      postare: string | null;
      updatecomponentsstockinfabrication: boolean;
      customersdeliveryorderpreparingquantity: number;
      customersreturnorderpreparingquantity: number;
      suppliersdeliveryorderpreparingquantity: number;
      suppliersreturnorderpreparingquantity: number;
      stockbillofquantitiesprogram_keepactivefromquotetoorder: boolean;
      purchasechargesrate: number;
      posisscale: boolean;
      postare: string | null;
      billofquantitiesprogram_program: string | null;
      replenishmentdeliveryaddresstype: number;
      saleunitpriceprogram_program: string | null;
      descom: string;
      descomclear: string;
      itemimage: string | null;
      barcode: string | null;
      unitid: string | null;
      familyid: string | null;
      subfamilyid: string | null;
      syscreateddate: string;
      syscreateduser: string;
      sysmodifieddate: string;
      sysmodifieduser: string;
      notesclear: string | null;
      notes: string | null;
      oxatis_oxatis_categorytype1: string | null;
      oxatis_oxatis_categorytype2: string | null;
      oxatis_oxatis_categorytype3: string | null;
      oxatis_oxatis_categoryid1: string | null;
      oxatis_oxatis_categoryid2: string | null;
      oxatis_oxatis_categoryid3: string | null;
      oxatis_oxatis_metatitle: string | null;
      oxatis_oxatis_metadescription: string | null;
      oxatis_oxatis_metakeywords: string | null;
      oxatis_oxatis_brand: string | null;
      mainintervener: string | null;
      intrastatnc8nomenclatureid: string | null;
      group1: string | null;
      group2: string | null;
      notprintable: boolean | null;
      notincluded: boolean | null;
      isfixedprice: boolean | null;
      noninvoiceabletype: number | null;
      componentcalculationtype: number | null;
      replacementitem: string | null;
      weightunitid: string | null;
      numberofitembypackage: number;
      volumeunitid: string | null;
      supplierid: string;
      ecotaxid: string | null;
      stockdestination: number;
      stockvarianceaccount: string;
      currentstockaccount: string;
      vatid: string;
      sysmoduleid: string | null;
      sysdatabaseid: string | null;
      sysrecordversion: number;
      sysrecordversionid: string;
      syseditcounter: number;
      limitdatesafetydelaymode: number | null;
      defaultlifetime: number | null;
      purchasepriceupdatetype: number | null;
      analyticaccounting_gridid: string | null;
      purchaseunitid: string | null;
      dimensionunitid: string | null;
      oxatis_oxatis_longdescription: string | null;
      oxatis_oxatis_longdescriptionclear: string | null;
      oxatis_oxatis_smallimage: string | null;
      purchasebillofquantitiesprogram_program: string | null;
      catalogid: string | null;
      catalogitemid: string | null;
      ecotaxfurnitureid: string | null;
      purchaseunitpriceprogram_program: string | null;
      localizablecaption_2: string | null;
      localizabledescom_2: string | null;
      localizabledescom_clear_2: string | null;
      localizablecaption_3: string | null;
      localizablecaption_4: string | null;
      localizablecaption_5: string | null;
      localizabledescom_3: string | null;
      localizabledescom_clear_3: string | null;
      localizabledescom_4: string | null;
      localizabledescom_clear_4: string | null;
      localizabledescom_5: string | null;
      localizabledescom_clear_5: string | null;
      intrastatorigincountryid: string | null;
      parentrangeitemid: string | null;
      rangetypeelementid0: string | null;
      rangetypeelementid1: string | null;
      rangetypeelementid2: string | null;
      rangetypeelementid3: string | null;
      rangetypeelementid4: string | null;
      defaultallowedstorehouseid: string | null;
      maintenancecontracttemplateid: string | null;
      guaranteetypeid: string | null;
      stockbillofquantitiesprogram_program: string | null;
      posthumbnail: string | null;
      giftvouchercashvalue: number | null;
      giftvouchervalidityduration: number | null;
      isextrafee: boolean;
      timeunitid: string | null;
      technicaldescom: string | null;
      technicaldescomclear: string | null;
      localizabletechnicaldescom_2: string | null;
      localizabletechnicaldescom_clear_2: string | null;
      localizabletechnicaldescom_3: string | null;
      localizabletechnicaldescom_clear_3: string | null;
      localizabletechnicaldescom_4: string | null;
      localizabletechnicaldescom_clear_4: string | null;
      localizabletechnicaldescom_5: string | null;
      localizabletechnicaldescom_clear_5: string | null;
      competenceid: string | null;
      equipmenttypeid: string | null;
      scheduleeventtemplateid: string | null;
      competencenumbertoplan: number | null;
      equipmenttypenumbertoplan: number | null;
      cadenceduration: number;
      cadencedurationtype: number;
      cadencedurationquantity: number;
      installationtime: number;
      labourcode: string | null;
      autoupdatelabourprice: boolean;
      isequipment: boolean;
      installationcalculationtype: number;
      materialprices_purchaseprice: number;
      materialprices_chargerate: number;
      materialprices_chargeamount: number;
      materialprices_costprice: number;
      materialprices_interestrate: number;
      materialprices_interestamount: number;
      materialprices_salepricevatexcluded: number;
      materialprices_brandrate: number;
      materialprices_vatid: string;
      materialprices_vatamount: number;
      materialprices_salepricevatincluded: number;
      materialprices_advisedsalepricevatexcluded: number;
      materialprices_setitemsalepricewithadvisedsaleprice: boolean;
      materialprices_isfixedprice: boolean | null;
      materialprices_ecotaxfurnitureid: string | null;
      labourprices_purchaseprice: number;
      labourprices_chargerate: number;
      labourprices_chargeamount: number;
      labourprices_costprice: number;
      labourprices_interestrate: number;
      labourprices_interestamount: number;
      labourprices_salepricevatexcluded: number;
      labourprices_brandrate: number;
      labourprices_vatid: string;
      labourprices_vatamount: number;
      labourprices_salepricevatincluded: number;
      labourprices_advisedsalepricevatexcluded: number;
      labourprices_setitemsalepricewithadvisedsaleprice: boolean;
      labourprices_isfixedprice: boolean | null;
      labourprices_ecotaxfurnitureid: string | null;
      canbepartiallyinvoiced: boolean;
      pickmovementdisallowedontotallybookeditem: boolean;
      salepricemodifieddate: string | null;
      salepricemodifieduserid: string | null;
      tarifeocode: string | null;
      tarifeofullcode: string | null;
      tarifeoproducerid: string | null;
      producername: string | null;
      tarifeopricedate: string | null;
      tarifeopriceversion: string | null;
      tarifeoupdatedatetime: string | null;
      issubscription: boolean;
      subscriptionpassings: number;
      subscriptiontotalcostprice: number;
      subscriptiontotalpurchaseprice: number;
      subscriptiontotalsalepricevatexcluded: number;
      subscriptionvalidityduration: number;
    
    }
  
    */
    
  
  
    